layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      Opeating-System-Lab-Work
      LyricSearch
      speller

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: jayaShankar2102
  hackerrank: bjayashankar2102
  # keybase: your_username
  medium: bjayashankar2102
  linkedin: jaya-shankar-bandaru-08032a192
  instagram: jaya_shankar_21_02
  # mastodon: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: AR
    web_url: https://www.youtube.com/watch?v=8hZkM4TgwZ4
    image_url: img/AR.jpeg

  - name: AI
    web_url: https://www.sas.com/en_in/insights/analytics/what-is-artificial-intelligence.html
    image_url: img/AI.jpeg

  - name: Back-end Development
    web_url: https://www.techopedia.com/definition/29568/back-end-developer
theme: jekyll-theme-cayman